In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
saldf=pd.read_csv("/content/drive/MyDrive/data sets /cardekho.csv")

In [3]:
saldf.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [4]:
saldf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                8128 non-null   object
 1   year                8128 non-null   int64
 2   selling_price       8128 non-null   int64
 3   km_driven           8128 non-null   int64
 4   fuel                8128 non-null   object
 5   seller_type         8128 non-null   object
 6   transmission        8128 non-null   object
 7   owner               8128 non-null   object
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB

In [5]:
saldf.isnull().sum()

name                    0
year                    0
selling_price           0
km_driven               0
fuel                    0
seller_type             0
transmission            0
owner                   0
mileage(km/ltr/kg)    221
engine                221
max_power             215
seats                 221
dtype: int64

In [6]:
saldf.isnull().sum()
saldf.dropna().sum()

name                  Maruti Swift Dzire VDISkoda Rapid 1.5 TDI Ambi...
year                                                           15924557
selling_price                                                5137507277
km_driven                                                     547105544
fuel                  DieselDieselPetrolDieselPetrolPetrolLPGPetrolD...
seller_type           IndividualIndividualIndividualIndividualIndivi...
transmission          ManualManualManualManualManualManualManualManu...
owner                 First OwnerSecond OwnerThird OwnerFirst OwnerF...
mileage(km/ltr/kg)                                            153544.32
engine                                                       11533348.0
max_power             74103.52789088.281.8657.53767.168.1108.456073....
seats                                                           42830.0
dtype: object

In [7]:
le=LabelEncoder()
saldf["selling_price"]=le.fit_transform(saldf["selling_price"])
saldf.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,282,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,229,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,94,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,136,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,74,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [8]:
le=LabelEncoder()
saldf["fuel"]=le.fit_transform(saldf["fuel"])
saldf.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,282,145500,1,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,229,120000,1,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,94,140000,3,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,136,127000,1,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,74,120000,3,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [9]:
inp=saldf[["fuel"]]
out=saldf[["selling_price"]]

In [10]:
LR=LinearRegression()

In [11]:
Train_data=pd.concat([inp,out],axis=1)
train=Train_data.dropna()

In [12]:
inp1=saldf[["fuel"]]
out1=saldf[["selling_price"]]

In [15]:
LR.fit(inp1,out1)

LinearRegression()

In [16]:
LinearRegression()
LR.predict([[5]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[133.90714187]])

In [18]:
saldf.to_pickle('saldf.pkl')

In [19]:
from google.colab import files
files.download('saldf.pkl')